color: null
fieldLayouts:
  4289b4b7-03ee-407f-8d0c-4bee41322dd9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T19:02:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67a9f4fd-1542-4c69-a51d-2e52fe7cf8a8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:04:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d56b297b-0f38-4dee-abc3-57498c544f41 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b79a264-961a-4f5e-9afb-aa7254ddd6cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:28:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3644b740-3500-418e-a08f-7e66e4a2b99e # Show Breadcrumbs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69a43a14-36b6-4093-a1db-1b59f845952f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:28:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 89dec5ed-967b-4adc-96f4-990fe7f52da5 # Breadcrumb Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b21fdd5e-b6a0-4941-a799-3a833b04a0db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b2b723b-2fe2-481e-9143-ffee8758507b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T19:04:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d7fd420-3fd4-4dc0-afca-1833e0d9a05c # SEOMatic Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01620449-cd9d-4b84-a9f0-459ea5d2eedc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:04:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 678939a0-3ca0-4044-b263-e25151ebb1df # Additional Header Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65589034-43f3-4049-87f7-d4208dc4d6f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:04:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e4455cb-a3c6-4a1f-aece-f5b32088a23e # Additional Footer Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc52e60d-1b3f-4027-bc4a-8eb1584f7fef
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 71ca8fd0-d210-40e9-ba9a-eeae261d1813
        userCondition: null
handle: blogPage
hasTitleField: true
icon: null
name: 'Blog Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
