color: null
fieldLayouts:
  25e832d4-be1c-41d4-836b-00f72ac16c5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T14:20:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 37581c39-ebd0-4472-aa61-c2f51a891535 # Content (No Media)
            handle: null
            includeInCards: false
            instructions: null
            label: Content
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f204a9b4-3e4b-4e3e-8174-3cd2a188635c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T15:33:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: 'Fill in link to create a CTA'
            label: 'CTA Link'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76f5a0da-a193-46ec-ace9-cce0fdc990f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: be2b67a6-33b2-46a1-846f-e1ffc52adbba
        userCondition: null
handle: callToAction
hasTitleField: false
icon: null
name: 'Call To Action'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
