color: null
fieldLayouts:
  515e0519-13d1-4342-b699-992300b32a05:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T19:04:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1f33c60e-5296-4b79-89a6-27e17879753c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:06:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d56b297b-0f38-4dee-abc3-57498c544f41 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62141048-f413-450e-a6f2-d75268866ef8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:28:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3644b740-3500-418e-a08f-7e66e4a2b99e # Show Breadcrumbs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10fc868a-b205-463b-9edd-6f960a30e64d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:28:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 89dec5ed-967b-4adc-96f4-990fe7f52da5 # Breadcrumb Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fcead36-284d-467d-a5a1-c1555d3fb101
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9496b43c-5c13-464b-be1b-e19d58800a18
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T19:06:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d7fd420-3fd4-4dc0-afca-1833e0d9a05c # SEOMatic Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98d63b2e-ded1-49dc-b7f3-20f9a1e7cfbd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:06:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 678939a0-3ca0-4044-b263-e25151ebb1df # Additional Header Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee07500a-1ed6-4da5-9a3d-6f841adffc52
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:06:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e4455cb-a3c6-4a1f-aece-f5b32088a23e # Additional Footer Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d675d3b9-153f-4007-9678-ebc27f8a8986
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 7bce169d-dd8b-4403-b5cb-df3c2600bcf0
        userCondition: null
handle: contactPage
hasTitleField: true
icon: null
name: 'Contact Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
