color: null
fieldLayouts:
  6e6b0216-5d3f-4f54-9de4-cac73ac59725:
    cardView:
      - 'layoutElement:131fb942-4184-4c34-bb2d-722a8619f59a'
      - 'layoutElement:d94a187a-a522-4c4c-b477-7c9d0ef1ebf9'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-19T15:13:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 131fb942-4184-4c34-bb2d-722a8619f59a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T15:09:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd58c3c0-4afc-4b83-a606-73c8bc282d99 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94a187a-a522-4c4c-b477-7c9d0ef1ebf9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-19T15:09:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ff11a7ef-4804-4699-9e26-f9d531a7e760 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a57189cc-9676-417a-862c-b71b73d7eddf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T15:35:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: 'Fill in link to create a CTA'
            label: 'CTA Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3514ac5b-f290-4824-bddc-107ca2234187
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a22b222b-3e6a-4f05-85cd-0916741299b0
        userCondition: null
handle: imageCard
hasTitleField: false
icon: null
name: 'Image Card'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
