color: lime
fieldLayouts:
  dbf6d4f8-51c7-4924-9747-da8670c51e61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-15T18:11:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd58c3c0-4afc-4b83-a606-73c8bc282d99 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d08175f-0237-45a4-b7a7-8441a7b3a2be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d2894de-76d5-4df2-980f-3f72f7e7dbc3
        userCondition: null
handle: image
hasTitleField: false
icon: null
name: Image
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
