color: orange
fieldLayouts:
  ba5da5df-3c24-44b2-a61a-e68b58533467:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-15T20:21:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3546d0c2-4446-4f19-beb3-1e460aa375df # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9930410-5e71-4ae4-8f87-cc564968dc04
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:21:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fe215cb-38e5-419d-8038-a1ccebf68878
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:21:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dab85477-9d74-4135-9cd2-a0e109e07314 # Subheadline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e52fc716-31f3-4af2-a7bd-ac01c1782728
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T20:41:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5217297d-5931-41b9-a7a4-a797bb339952 # Logos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30b6394c-97dc-4b5a-807c-b612c4c38fd1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T15:35:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: 'Fill in link to create a CTA'
            label: 'CTA Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6345697c-5860-4cf9-ae7e-e3c595661c78
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3f9b8a3-d83e-4e75-8e90-1e202868c302
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-15T20:21:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a7b59ddf-b06d-4b04-8d73-c52609ae95d3 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e32c7188-d89d-484d-9c8d-55e6955ac556
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 41b56885-307a-42c8-a285-d7be4487c4c0
        userCondition: null
handle: logoGridSection
hasTitleField: false
icon: null
name: 'Logo Grid'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
