color: indigo
fieldLayouts:
  10a76dce-118a-42ab-ae61-06ddbc0dadd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T14:57:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3546d0c2-4446-4f19-beb3-1e460aa375df # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df8b6e6f-f6ba-497d-a35c-1afbe2096017
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T14:57:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4903969a-2b49-4984-979e-6f0ab4c238c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T14:57:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dab85477-9d74-4135-9cd2-a0e109e07314 # Subheadline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 239636d6-2511-4e4b-9ecc-52761402f8dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T14:57:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 850e8e38-809a-494d-b643-efd7ff7c48e6 # Media Sub Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04f6a9aa-cc09-4745-8012-926262ab1481
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T14:57:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: 'Fill in link to create a CTA'
            label: 'CTA Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd295e4e-7d7a-44b4-9f10-0f61a4ad8b46
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eb4e437b-df66-45d6-851e-38a858af1f56
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-19T14:56:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f694951-45bb-48bb-8b85-e0d8634e227c # Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd9eba28-273f-4a36-969c-fbbba1453e3e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-19T14:56:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a7b59ddf-b06d-4b04-8d73-c52609ae95d3 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98b84bfa-5af9-4977-991c-f51e17838b61
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 171c531a-728b-4417-b178-c7f60f05e056
        userCondition: null
handle: mediaSection
hasTitleField: false
icon: null
name: 'Media Section'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
