color: blue
description: null
fieldLayouts:
  1d2aa3ee-b9ed-408a-9c86-15f732695675:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-22T13:25:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cfef99ee-464a-452e-b731-e56f774b997a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e3f62f13-f5a3-46c5-8041-e3bf098500ab
        userCondition: null
handle: navItem
hasTitleField: false
icon: null
name: 'Navigation Item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
