color: null
fieldLayouts:
  bfa1f8d8-43d5-464f-b53e-9d21a97dbd21:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T19:00:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1460880d-9e4d-4b51-9e46-a5f895c315df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:01:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d56b297b-0f38-4dee-abc3-57498c544f41 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a23ece3d-eb23-44f5-94c7-4c5d25f46ae9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:29:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3644b740-3500-418e-a08f-7e66e4a2b99e # Show Breadcrumbs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01a65a3f-7661-426d-be82-ad55b4ba7983
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:29:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 89dec5ed-967b-4adc-96f4-990fe7f52da5 # Breadcrumb Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9fe79604-3c52-4093-9f7a-1a41a03251ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eb7088c6-6660-4f5d-9740-bf882f1d8273
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T19:01:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d7fd420-3fd4-4dc0-afca-1833e0d9a05c # SEOMatic Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae596ff2-9d7a-4491-9d10-1fdae9897249
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:01:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 678939a0-3ca0-4044-b263-e25151ebb1df # Additional Header Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd412549-b841-446f-811b-8364c2c369eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:01:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e4455cb-a3c6-4a1f-aece-f5b32088a23e # Additional Footer Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e869a3f0-29f8-4f10-8ed3-af03ff212233
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8baf20f8-1b01-4771-80be-45c2c8e29dee
        userCondition: null
handle: newsPage
hasTitleField: true
icon: null
name: 'News Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
