color: null
fieldLayouts:
  c55236ad-7020-4efe-9e83-a1c2111803a6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T19:03:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2103b858-9465-450d-85ce-7cce22005592
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:05:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d56b297b-0f38-4dee-abc3-57498c544f41 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c8e02e8-397d-4cb4-b489-050ac0ead364
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:25:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3644b740-3500-418e-a08f-7e66e4a2b99e # Show Breadcrumbs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0eb591ac-c2fc-4db9-a9ac-70eed095f814
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-15T13:25:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 89dec5ed-967b-4adc-96f4-990fe7f52da5 # Breadcrumb Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9da16ee3-f6f1-48db-baa3-1569ab250a6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 394a5a27-e0d3-45a0-b416-00930c6a3c5c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-18T19:05:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1d7fd420-3fd4-4dc0-afca-1833e0d9a05c # SEOMatic Fields
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdbb16b2-8424-4a29-8d27-90ad9ecb1a6a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:05:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 678939a0-3ca0-4044-b263-e25151ebb1df # Additional Header Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f1d424c-f889-43ca-b473-41f9c177c0e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-18T19:05:28+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e4455cb-a3c6-4a1f-aece-f5b32088a23e # Additional Footer Code
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 248b0045-f3fa-4d9d-8bbc-6a0f66c9fe6c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d3506e03-f69f-4dc0-9e0c-b576a613729d
        userCondition: null
handle: teamPage
hasTitleField: true
icon: null
name: 'Team Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
