color: sky
fieldLayouts:
  0a5eb646-9689-4454-8f84-a9815142c0ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-15T17:02:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3546d0c2-4446-4f19-beb3-1e460aa375df # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74f3a028-f488-444d-9f5e-c5cf5a97ce3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T17:02:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3984cd0f-a133-49ff-94d0-63730cf1bf51 # Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f430633-62a8-44bb-93cb-4da3c4036f48
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T17:02:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dab85477-9d74-4135-9cd2-a0e109e07314 # Subheadline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eac65eca-e16a-4cef-98df-9353df2bdbc4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T19:03:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 866793e8-8646-486d-95c2-24ad883f46a7 # Sub Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2e0c206-e683-4581-8b92-0297f407c99d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T15:32:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a53a4fd-6824-4729-9a20-006558d3e221 # Link
            handle: null
            includeInCards: false
            instructions: 'Fill in link to create a CTA'
            label: 'CTA Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df5ef9c8-7e41-4dc8-bdc9-22db4d36788f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0355b2e8-6e94-44c3-85e7-15230078b004
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-08T20:45:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f694951-45bb-48bb-8b85-e0d8634e227c # Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38385629-a661-417f-9bb7-0d4dbef8b9fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T17:02:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a7b59ddf-b06d-4b04-8d73-c52609ae95d3 # Anchor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f9770ea-fe09-4147-b7c4-de5b18682064
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: f736d5ff-5c94-4017-b4d9-d33cf1ea3003
        userCondition: null
handle: twoColumnSection
hasTitleField: false
icon: null
name: 'Two Column Section'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
