color: amber
fieldLayouts:
  adb58e3b-a1c7-48d3-a0ea-9285a000fbd7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-20T01:40:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dd58c3c0-4afc-4b83-a606-73c8bc282d99 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: 'Thumbnail Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fe7f3bd-8d51-437a-94f1-7e0de56e58af
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-15T19:02:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 56554df0-f81a-4c6a-b023-706d2789eaa9 # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e66c4c1-1d62-4659-9ba7-294fbd16236c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 348db75c-74e1-427a-8a20-a5d0ef4ffa91
        userCondition: null
handle: video
hasTitleField: false
icon: null
name: Video
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
