headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'No Media'
options:
  link:
    decorators:
      isExternal:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
  style:
    definitions:
      -
        classes:
          - '-gray'
        element: p
        name: 'Gray text'
toolbar:
  - heading
  - style
  - '|'
  - numberedList
  - bulletedList
  - bold
  - italic
  - link
  - undo
  - redo
  - htmlEmbed
