columnSuffix: null
handle: ctaLink
instructions: 'Leave blank to create a heading with no link'
name: Link
searchable: true
settings:
  advancedFields:
    - target
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - '1'
            -
              - showUnpermittedEntries
              - '1'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - '1'
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
    - asset
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
