columnSuffix: null
handle: footerNavItems
instructions: null
name: 'Footer Navigation Items'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\LevelConditionRule
              -
                - uid
                - 7b9f25b9-7af8-40e2-b4a1-a7d23089cda8
              -
                - operator
                - '='
              -
                - value
                - '1'
              -
                - maxValue
                - ''
              -
                - step
                - 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:0e0a0c15-2d54-4a63-b4ae-29b75916437e' # Navigation
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
