columnSuffix: null
handle: heroContent
instructions: null
name: 'Hero Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: dccf2895-2f61-4bbe-8ac6-bf389ab04527 # Simple (No Links)
  createButtonLabel: null
  defaultTransform: null
  fullGraphqlData: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
