columnSuffix: null
handle: navItems
instructions: null
name: 'Navigation Items'
searchable: false
settings:
  createButtonLabel: 'New item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - c7e04c91-15c1-4081-8d31-44ae7bf6eae9 # Navigation Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
