fieldLayouts:
  3029a860-09a3-4562-9ce4-2e8580d699ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-06T18:25:26+00:00'
            elementCondition: null
            fieldUid: d26a5c7a-435f-4562-91fe-d168201e7bed # Footer Navigation Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47dc35ef-69cb-443a-83e8-8413188eee9c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08ec1209-3049-4e39-9d53-da610da5d938
        userCondition: null
handle: footerNavigation
name: 'Footer Navigation'
sortOrder: 2
